name: Sync labels
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: 📑 Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - name: 🔄 Sync labels
        uses: devantler-tech/composite-actions/sync-labels-action@44620f6c6e9bc2046c7959932fbd104a74d6b1a5 # v1.9.1
